name: Run pdk validate

# only run pdk validation on push/merge to one of the primary branches
on:
  push:
    branches:
      - master
      - main
      - production
      - nonprod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run pdk validate
      uses: puppets-epic-show-theatre/action-pdk-validate@v1
      with:
        # [optional]
        # A string indicating the Puppet version to validate against, such as "5.4.2" or "5.5".
        puppet-version: ""
        # [optional]
        # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
        pe-version: ""
